### ISSUE TITLE
father-build error

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/DragAndDrop#1]
`yarn && yarn run build`

```bash
Build umd
'domain' is imported by node_modules/asap/raw.js, but could not be resolved – treating it as an external dependency
'domain' is imported by domain?commonjs-external, but could not be resolved – treating it as an external dependency
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragSource.js -> node_modules/react-dnd/dist/esm/decorators/decorateHandler.js -> node_modules/react-dnd/dist/esm/index.js
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragLayer.js -> node_modules/react-dnd/dist/esm/index.js
'createContext' is not exported by 'node_modules/react/index.js'
✖  error     Error: 'memo' is not exported by node_modules/react/index.js 
    at error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:9365:30)
    at Module.error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13271:9)
    at handleMissingExport (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13194:21)
    at Module.traceVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13573:17)
    at ModuleScope.findVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:12293:39)
    at Identifier$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:8313:40)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7949:23)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:10300:15)
    at VariableDeclarator.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7949:23)
    at VariableDeclaration$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7945:31)
error Command failed with exit code 1.
```

**Comment by xiaohuoni** [comment]
@sorrycc 
配置 `namedExports` 错一个写一个，最终。
```
namedExports: { 'react': ['useRef', 'useMemo', 'isValidElement', 'createContext', 'memo', 'useLayoutEffect', 'useEffect', 'createElement', 'useState', 'useCallback', 'useContext', 'cloneElement'] },
```
错误日志如下
```bash
Clean dist directory
Build umd
'domain' is imported by node_modules/asap/raw.js, but could not be resolved – treating it as an external dependency
'domain' is imported by domain?commonjs-external, but could not be resolved – treating it as an external dependency
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragSource.js -> node_modules/react-dnd/dist/esm/decorators/decorateHandler.js -> node_modules/react-dnd/dist/esm/index.js
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragLayer.js -> node_modules/react-dnd/dist/esm/index.js
'createRef' is not exported by 'node_modules/react/index.js'
'Component' is not exported by 'node_modules/react/index.js'
'createRef' is not exported by 'node_modules/react/index.js'
'Component' is not exported by 'node_modules/react/index.js'
No name was provided for external module 'domain' in output.globals – guessing 'domain$1'
Creating a browser bundle that depends on Node.js built-in module ('domain'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
'domain' is imported by node_modules/asap/raw.js, but could not be resolved – treating it as an external dependency
'domain' is imported by domain?commonjs-external, but could not be resolved – treating it as an external dependency
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragSource.js -> node_modules/react-dnd/dist/esm/decorators/decorateHandler.js -> node_modules/react-dnd/dist/esm/index.js
Circular dependency: node_modules/react-dnd/dist/esm/index.js -> node_modules/react-dnd/dist/esm/decorators/index.js -> node_modules/react-dnd/dist/esm/decorators/DragLayer.js -> node_modules/react-dnd/dist/esm/index.js
'createRef' is not exported by 'node_modules/react/index.js'
'Component' is not exported by 'node_modules/react/index.js'
'createRef' is not exported by 'node_modules/react/index.js'
'Component' is not exported by 'node_modules/react/index.js'
No name was provided for external module 'domain' in output.globals – guessing 'domain$1'
Creating a browser bundle that depends on Node.js built-in module ('domain'). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins
Build cjs with rollup
✖  error     Error: 'default' is not exported by node_modules/react/index.js 
    at error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:9365:30)
    at Module.error (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13271:9)
    at handleMissingExport (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13194:21)
    at Module.traceVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:13573:17)
    at ModuleScope.findVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:12293:39)
    at FunctionScope.findVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:2961:38)
    at ChildScope.findVariable (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:2961:38)
    at MemberExpression.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:11223:49)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:7949:23)
    at CallExpression$1.bind (/Users/xiaohuoni/DragAndDrop/node_modules/rollup/dist/rollup.js:10300:15)
error Command failed with exit code 1.
```

**Comment by wangxingkang** [comment]
要不要试一试 @walrus/pansy 哈哈

**Comment by xiaohuoni** [comment]
@wangxingkang 不要，这里附带测试了 father-doc 的功能

**Comment by sorrycc** [comment]
`@walrus/pansy` 如何解决 umd 包下 namedExports 的问题？

**Comment by wangxingkang** [comment]
没关注这块 我研究一下
